name: build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github"
      - ".vscode"
      - "scripts"
      - "README.md"
      - ".env.example"
      - ".gitignore"
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      TARGET: "x86_64-unknown-linux-gnu"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deno dependencies
        run: deno install

      - name: Build Deno application
        run: deno task bundle && deno task compile:linux

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ env.TARGET }}

      - name: Build Rust application
        run: cargo build --release --target $TARGET

      - name: Create dist
        run: |
          mkdir -p dist
          cp build/xdwlan-login-worker dist
          cp target/$TARGET/release/xdwlan-login dist
          cp config.example.yaml dist/config.yaml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: dist
          retention-days: 2

  build-windows:
    runs-on: windows-latest
    env:
      TARGET: "x86_64-pc-windows-msvc"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deno dependencies
        run: deno install

      - name: Build Deno application
        run: deno task bundle && deno task compile:windows

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ env.TARGET }}

      - name: Build Rust application
        run: cargo build --release --target $env:TARGET

      - name: Create dist
        run: |
          New-Item -ItemType Directory -Path dist
          Copy-Item build/xdwlan-login-worker.exe -Destination dist
          Copy-Item target/$env:TARGET/release/xdwlan-login.exe -Destination dist
          Copy-Item config.example.yaml -Destination dist/config.yaml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: dist
          retention-days: 2
