name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases and uploading assets
      actions: read # Required for accessing workflow artifacts
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download linux artifact
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Set node
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*

      - name: Generate changelog
        run: npx changelogithub@13.13.0 --output dist/CHANGELOG.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            dist/xdwlan-login-x86_64-unknown-linux-gnu.tar.xz
            dist/xdwlan-login-x86_64-pc-windows-msvc.zip
          fail_on_unmatched_files: true
          body_path: dist/CHANGELOG.md
